---
name: Lint Code Base

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        # uses: super-linter/super-linter/slim@12150456a73e248bdc94d0794898f94e23127c88 # 7.4.0
        uses: super-linter/super-linter/slim@61abc07d755095a68f4987d1c2c3d1d64408f1f9 # v8.5.0
        # Can't move on to super-linter v8.x yet due to Drupal core still using airbnb-base eslint config
        # https://www.drupal.org/project/drupal/issues/3440225
        # https://github.com/super-linter/super-linter/blob/main/docs/upgrade-guide.md#removed-eslint-plugins-and-configurations

        env:
          LINTER_RULES_PATH: .github/linters
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_PHP_PSALM: false
          VALIDATE_PHP_PHPCS: false
          # YAML is validated via eslint plugin for Drupal
          VALIDATE_YAML_PRETTIER: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
